apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-cm
  namespace: datahub
data:
  DATAHUB_GMS_URL: "http://datahub-datahub-gms:8080"
  DRY_RUN: "false"
  BATCH_SIZE: "100"
  TAG_NAME: "needs-owner"
  TAG_DESCRIPTION: "Dataset has no assigned owner and requires one."