---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-secret
  namespace: datahub
spec:
  encryptedData:
    DATAHUB_TOKEN: AgBGbTgzzzVjtDGuBU1SXaFjWxnIvRq2n1BqYDj4W0ZReOHwxy5CZYoAeTsC3vkqaznQASLDQtCazbi3R3Vt66991jJdOL6w88OyDVfQY/y5Ib0bADJjYFPgRkANWoUOiBg4mSrF6IWrl3Tibb1GFjOzogxKVEB9BUZXflnVywd1RZykcSxPlnKzCEUGhlPmtw3GbDfr1I8Cp+Ic+Hlx+DhOrXIho446/oSx0q9Ky2xgb1KQbN3W7BP0LPNd+dYX8uNKR037TjjNncq2k7CCOlT4qYleHIT4bHUf/Gjx4mwEc4Mq2boPwS6379aXTbpoMjhdLf/HFcpcO5110n9ct7LuaAz9m/9OEefnGlohB3HZjrb7fyaLfGjA00DfpCRfSGKFCs/1FN9WzIJgJrp5VeQwgkjEagck1jHZVW4Vkpf6FxZD1O2ABC2/PCqxX8ZMG5Y9yjCqDzdc5zwWvOpujJkolBwaOICaAg2uNZxSdPIfnYuIJZxOd6my8G3+YwXuqZMBL9qlqnS5EaulKdjnexK3+4FR66WCbdxEBl02mQajpff6EerlqOOOb+E/kQLIqIxuE5ZnYDL0q91dAeCnmOFC3meuEKNI2aClnTLn+OEt+Mb5mj1xHCJ1Zc5ZVUxYanP2h/xzVuqEl4lmAlgebrFwnHA09+Mr248eCJ1//sW56EMnrfHNtV9srTB2C4p4yVMhxDzNVtuVwUqWQdKF/AQm3MvZwOEgkD3SX58pVvN0bD6N/T8sF0j5C9OU1me1fPO6TjP+tCAiiKPnnuE6sE65rGoFWP8rXIl94N5m+2Nxc+MiYI0TX9SjOvwtUIToLN1NGkCSh3TjFesS/P5wdMmUNplUBZDkdMz27KOpACyJ/xWJwKKSjdBodZkkPayi+xv+Z2/CualLVZdhOjuQnPuu1sWZAMpcSSQfdfqMVUjFk09IbZF+YstiNoUtvjS+4GhzHUpEKA4G2PqkxHh7DJFiJQaU1Amc1vtYnJjYGOBXnM1mdim2BQvUShtQIEgUuioW0M+gpS1t8s7sGf3UTh1XjdWMSkYeyOkT9oQnzYjWcFY7uz49rwtgjvp38GExQVFz7liOSj3kHAo7oSmgnEytTnKux7o=
  template:
    metadata:
      name: cronjob-secret
      namespace: datahub
    type: Opaque
